# Generated by Django 3.1.2 on 2020-11-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralInformation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_information',
            name='factory_date',
            field=models.BooleanField(default=False),
        ),
    ]
